Removed docs for #11515
SAP/spartacus-docs pull request #1122
Opened 2021-05-07 16:08 UTC by ren-tham

4.0 deprecation ticket: https://github.com/SAP/spartacus/issues/11515

Removing docs for deprecated classes.

2021-05-07 16:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/spartacus-docs?pullRequest=1122) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/spartacus-docs?pullRequest=1122) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/spartacus-docs?pullRequest=1122) it.</sub>

2021-05-13 13:21 UTC, WeizhengSap commented
Please don't remove the doc, but remove the part <4.0.

2021-05-13 13:39 UTC, WeizhengSap requested changes
don't remove this doc, but remove the part < 4.0

2021-06-29 15:44 UTC, gladius-mtl commented
Update was done manually.

2021-06-29 15:44 UTC, closed without merging